version: '3'

services:
  backend:
    build:
      context: ./django
    command: gunicorn backend.wsgi --bind 0.0.0.0:5000 --worker-class gthread --workers 2 --timeout 0
    ports:
      - "5000:5000"
    expose:
      - "5000"  

  frontend:
    build:
      context: ./react 
    volumes:
      - react_build:/react/build 
    stdin_open: true  
    expose:
      - "3000"  

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"     
    # expose:
    #   - "80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend
      
volumes:
  react_build:   